CREATE VIEW [SalesReport].[FactSales1]
AS SELECT    fs.[Sale Key]
            ,fs.[City Key]
            ,fs.[Customer Key]
            ,fs.[Bill To Customer Key]
            ,fs.[Stock Item Key]
            ,fs.[Invoice Date Key]
            ,fs.[Delivery Date Key]
            ,fs.[Salesperson Key]
            ,fs.[WWI Invoice ID]
            ,fs.[Description]
            ,fs.[Package]
            ,fs.[Quantity]
            ,fs.[Unit Price]
            ,fs.[Tax Rate]
            ,fs.[Total Excluding Tax]
            ,fs.[Tax Amount]
            ,fs.[Profit]
            ,fs.[Total Including Tax]
            ,fs.[Total Dry Items]
            ,fs.[Total Chiller Items]
            ,ft.[Payment Method Key]
--            ,[Lineage Key]
FROM [WWI_Warehouse].[dbo].[Fact Sale] as fs
JOIN [WWI_Warehouse].[dbo].[Fact Transaction] as ft
ON fs.[WWI Invoice ID] = ft.[WWI Invoice ID]